openapi: 3.0.0
info:
    title: Weather App API
    description: API for a Flask-based weather application
    version: 0.0.1
# servers:
#     - url: /api
paths:
    /weather/current/:
        get:
            summary: Get current weather for a location
            operationId: controllers.weather.get_current_weather
            parameters:
                - name: location
                  in: query
                  required: true
                  description: City name or zip code
                  schema:
                      type: string
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CurrentWeatherResponse"
                "400":
                    description: Invalid location
                "404":
                    description: Location not found
                "500":
                    description: Server error or weather service unavailable

components:
    schemas:
        CurrentWeatherResponse:
            type: object
            properties:
                location:
                    $ref: "#/components/schemas/Location"
                current:
                    $ref: "#/components/schemas/CurrentWeather"

        Location:
            type: object
            properties:
                name:
                    type: string
                region:
                    type: string
                country:
                    type: string
                lat:
                    type: number
                    format: float
                lon:
                    type: number
                    format: float
                tz_id:
                    type: string
                localtime_epoch:
                    type: integer
                localtime:
                    type: string
                    format: date-time

        CurrentWeather:
            type: object
            properties:
                last_updated_epoch:
                    type: integer
                last_updated:
                    type: string
                    format: date-time
                temp_c:
                    type: number
                    format: float
                temp_f:
                    type: number
                    format: float
                is_day:
                    type: integer
                    enum: [0, 1]
                condition:
                    $ref: "#/components/schemas/Condition"
                wind_mph:
                    type: number
                    format: float
                wind_kph:
                    type: number
                    format: float
                wind_degree:
                    type: integer
                wind_dir:
                    type: string
                pressure_mb:
                    type: number
                    format: float
                pressure_in:
                    type: number
                    format: float
                precip_mm:
                    type: number
                    format: float
                precip_in:
                    type: number
                    format: float
                humidity:
                    type: integer
                cloud:
                    type: integer
                feelslike_c:
                    type: number
                    format: float
                feelslike_f:
                    type: number
                    format: float
                windchill_c:
                    type: number
                    format: float
                windchill_f:
                    type: number
                    format: float
                heatindex_c:
                    type: number
                    format: float
                heatindex_f:
                    type: number
                    format: float
                dewpoint_c:
                    type: number
                    format: float
                dewpoint_f:
                    type: number
                    format: float
                vis_km:
                    type: number
                    format: float
                vis_miles:
                    type: number
                    format: float
                uv:
                    type: number
                    format: float
                gust_mph:
                    type: number
                    format: float
                gust_kph:
                    type: number
                    format: float

        Condition:
            type: object
            properties:
                text:
                    type: string
                icon:
                    type: string
                code:
                    type: integer
